// layout.js
import { JetBrains_Mono } from 'next/font/google';
import './globals.css';

import Header from '@/component/Header';
const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.className}>
<Header/>
       {children}
        </body>
    </html>
  );
}
